---
layout: question
title:  Node.js最佳实践异常处理
date:   2020-03-14T04:42:36.000Z
description: 几天前我才开始尝试使用node.js。我意识到只要程序中有未处理的异常，Node就会终止。这与我所见过的普通服务器容器不同，在发生未处理的异常时，只有工作...
img: 
author: L前端
category: question
answer: 5
tags: node.js Node.js
topic: Node.js
---
<div class="article-root">
  <div class="article">
    {% include articleTitle.html info=page %}
    {% raw %}
    <div class="article-content"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">几天前我才开始尝试使用node.js。</font><font style="vertical-align: inherit;">我意识到只要程序中有未处理的异常，Node就会终止。</font><font style="vertical-align: inherit;">这与我所见过的普通服务器容器不同，在发生未处理的异常时，只有工作线程会死亡，并且该容器仍将能够接收该请求。</font><font style="vertical-align: inherit;">这引起了一些问题：</font></font></p>

<ul>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">为</font></font><code>process.on('uncaughtException')</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">防范它的唯一有效途径？</font></font></li>
<li><font style="vertical-align: inherit;"></font><code>process.on('uncaughtException')</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">在异步过程执行期间是否</font><font style="vertical-align: inherit;">还会</font><font style="vertical-align: inherit;">捕获未处理的异常？</font></font></li>
<li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">是否存在已经构建的模块（例如发送电子邮件或写入文件），在未捕获的异常的情况下可以利用该模块？</font></font></li>
</ul>

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我将不胜感激任何向我展示在node.js中处理未捕获异常的常见最佳实践的指针/文章</font></font></p></div>
    {% endraw %}
  </div>
  <p class="winter_mark">第1577篇《Node.js最佳实践异常处理》来自Winter(https://github.com/aiyld/aiyld.github.io)的站点</p>
  <div class="discuss-wrapper">
    {% include discussTitle.html info=page %}
    {% raw %}
    <div class="discuss-list">
    <div class="discuss-item">
        <div class="discuss-parent">
          <div class="discuss-meta">
            <span class="discuss-user">樱小卤蛋</span>
            <span class="discuss-time">2020.03.14</span>
          </div>
          <div class="discuss-comment"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">如果要在Ubuntu（Upstart）中使用服务：将</font></font><a href="http://jacobmumm.com/2011/08/29/node-as-a-service-in-ubuntu-11-04-with-upstart-monit-and-forever-js/" rel="nofollow"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">节点作为服务在Ubuntu 11.04中使用upstart，monit和forever.js。</font></font></a></p></div>
        </div></div><div class="discuss-item">
        <div class="discuss-parent">
          <div class="discuss-meta">
            <span class="discuss-user">Jim老丝梅</span>
            <span class="discuss-time">2020.03.14</span>
          </div>
          <div class="discuss-comment"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">前一段时间看完这篇文章后，我想知道在api /函数级别使用域进行异常处理是否安全。</font><font style="vertical-align: inherit;">我想用它们来简化我编写的每个异步函数中的异常处理代码。</font><font style="vertical-align: inherit;">我担心的是，为每个功能使用新的域会带来大量的开销。</font><font style="vertical-align: inherit;">我的作业似乎表明，开销最小，在某些情况下，使用域实际上比使用try catch具有更好的性能。</font></font></p>

<p><a href="http://www.lighthouselogic.com/#/using-a-new-domain-for-each-async-function-in-node/" rel="nofollow"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">http://www.lighthouselogic.com/#/using-a-new-domain-for-each-async-function-in-node/</font></font></a></p></div>
        </div></div><div class="discuss-item">
        <div class="discuss-parent">
          <div class="discuss-meta">
            <span class="discuss-user">L理查德</span>
            <span class="discuss-time">2020.03.14</span>
          </div>
          <div class="discuss-comment"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我只想补充一下，</font></font><a href="https://github.com/creationix/step" rel="nofollow"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Step.js库</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">通过始终将其传递给下一步函数来帮助您处理异常。</font><font style="vertical-align: inherit;">因此，您可以在最后一步拥有一个功能，该功能可以检查前面任何步骤中的任何错误。</font><font style="vertical-align: inherit;">这种方法可以大大简化您的错误处理。</font></font></p>

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">以下是github页面的引文：</font></font></p>

<blockquote>
  <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">捕获所有抛出的异常，并将其作为第一个参数传递给下一个函数。</font><font style="vertical-align: inherit;">只要您不将回调函数嵌套到主函数中，就可以防止未捕获的异常。</font><font style="vertical-align: inherit;">这对于长时间运行的node.JS服务器非常重要，因为单个未捕获的异常会导致整个服务器宕机。</font></font></p>
</blockquote>

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">此外，您可以使用“步骤”来控制脚本的执行，以将清理部分作为最后一步。</font><font style="vertical-align: inherit;">例如，如果您想在Node中编写一个构建脚本并报告编写花费了多长时间，那么最后一步可以做到这一点（而不是尝试挖掘出最后一个回调）。</font></font></p></div>
        </div></div><div class="discuss-item">
        <div class="discuss-parent">
          <div class="discuss-meta">
            <span class="discuss-user">Davaid阳光小卤蛋</span>
            <span class="discuss-time">2020.03.14</span>
          </div>
          <div class="discuss-comment"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">我最近在</font></font><a href="http://snmaynard.com/2012/12/21/node-error-handling/"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">http://snmaynard.com/2012/12/21/node-error-handling/上</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">撰写了有关此内容的文章</font><font style="vertical-align: inherit;">。</font><font style="vertical-align: inherit;">域0.8版中节点的一项新功能是域，它使您可以将所有错误处理形式组合为一个更易于管理的形式。</font><font style="vertical-align: inherit;">您可以在我的文章中阅读有关它们的信息。</font></font></p>

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">您还可以使用</font></font><a href="https://bugsnag.com"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Bugsnag之</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">类的</font><a href="https://bugsnag.com"><font style="vertical-align: inherit;">东西</font></a><font style="vertical-align: inherit;">来跟踪未捕获的异常，并通过电子邮件，聊天室收到通知，或者为未捕获的异常创建票证（我是Bugsnag的共同创始人）。</font></font></p></div>
        </div></div><div class="discuss-item">
        <div class="discuss-parent">
          <div class="discuss-meta">
            <span class="discuss-user">西门十三LEY</span>
            <span class="discuss-time">2020.03.14</span>
          </div>
          <div class="discuss-comment"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">您可以捕获未捕获的异常，但是用途有限。</font><font style="vertical-align: inherit;">参见</font></font><a href="http://debuggable.com/posts/node-js-dealing-with-uncaught-exceptions:4c933d54-1428-443c-928d-4e1ecbdd56cb" rel="noreferrer"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">http://debuggable.com/posts/node-js-dealing-with-uncaught-exceptions:4c933d54-1428-443c-928d-4e1ecbdd56cb</font></font></a></p>

<p><code>monit</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">，</font></font><code>forever</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">或者</font></font><code>upstart</code><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">可用于在崩溃时重新启动节点进程。</font><font style="vertical-align: inherit;">正常关机是您所希望的（例如，将所有内存数据保存在未捕获的异常处理程序中）。</font></font></p></div>
        </div></div>
    </div>
    {% endraw %}
  </div>
<div>
